{{- $containerMode := .Values.containerMode }}
{{- if and (eq $containerMode.type "kubernetes") (not .Values.template.spec.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gha-runner-scale-set.kubeModeServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.containerMode.kubernetesModeServiceAccount }}
  {{- with .Values.containerMode.kubernetesModeServiceAccount.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
    argocd.argoproj.io/sync-options: Delete=false
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
  {{- end }}
  finalizers:
    - actions.github.com/cleanup-protection
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
{{- end }}
