{{- $containerMode := .Values.containerMode }}
{{- if and (ne $containerMode.type "kubernetes") (not .Values.runner.serviceAccountName) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gha-runner-scale-set.noPermissionServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gha-runner-scale-set.labels" . | nindent 4 }}
  finalizers:
    - actions.github.com/cleanup-protection
{{- end }}
