apiVersion: v2
name: actions-runner-controller
description: A Kubernetes controller that operates self-hosted runners for GitHub Actions on your Kubernetes cluster.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.18.0

# Used as the default manager tag value when no tag property is provided in the values.yaml
appVersion: 0.23.0

home: https://github.com/actions-runner-controller/actions-runner-controller

sources:
  - https://github.com/actions-runner-controller/actions-runner-controller

maintainers:
  - name: actions-runner-controller
    url: https://github.com/actions-runner-controller
