apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gha-controller.manager-listener-role-binding" . }}
  namespace: {{ include "gha-runner-scale-set-controller.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gha-controller.manager-listener-role-name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "gha-runner-scale-set-controller.serviceAccountName" . }}
  namespace: {{ include "gha-runner-scale-set-controller.namespace" . }}