# Set actions-runner-controller settings for testing
githubAPICacheDuration: 10s
logLevel: "-3"
githubWebhookServer:
  logLevel: "-3"
  enabled: true
  labels: {}
  replicaCount: 1
  syncPeriod: 10m
  useRunnerGroupsVisibility: true
  secret:
    enabled: true
    # create: true
    name: "github-webhook-server"
    ### GitHub Webhook Configuration
    #github_webhook_secret_token: ""
  service:
    type: NodePort
    ports:
      - port: 80
        targetPort: http
        protocol: TCP
        name: http
        nodePort: 31000
