apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "actions-runner-controller.labels" . | nindent 4 }}
  name: {{ include "actions-runner-controller.authProxyServiceName" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  {{- if .Values.kube_rbac_proxy.enabled }}
  - name: https
    port: 8443
    targetPort: https
  {{- else }}
  - name: http
    port: 8080
    targetPort: http
  {{- end }}
  selector:
    {{- include "actions-runner-controller.selectorLabels" . | nindent 4 }}
