{{- if eq .Values.flags.skipRbacSetup false }}
{{- if .Values.flags.watchSingleNamespace }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gha-runner-scale-set-controller.managerSingleNamespaceWatchRoleName" . }}
  namespace: {{ .Values.flags.watchSingleNamespace }}
rules:
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalingrunnersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunnersets/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners/finalizers
  verbs:
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - ephemeralrunners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - actions.github.com
  resources:
  - autoscalinglisteners
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - list
  - watch
  - patch
{{- end }}
{{- end }}
