name: Build and Release Runners

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'runner/**'
      - .github/workflows/build-and-release-runners.yml
  push:
    branches:
      - master
    paths:
      - runner/patched/*
      - runner/Dockerfile
      - runner/dindrunner.Dockerfile
      - runner/entrypoint.sh
      - .github/workflows/build-and-release-runners.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: actions-runner
            dockerfile: Dockerfile
          - name: actions-runner-dind
            dockerfile: dindrunner.Dockerfile
    env:
      RUNNER_VERSION: 2.277.1
      DOCKER_VERSION: 19.03.12
      DOCKER_QUAY_REPO: quay.io/sundae/actions-runner
    steps:
      - name: Set Outputs
        id: vars
        run: echo ::set-output name=sha_short::${GITHUB_SHA::7}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build Image
        uses: redhat-actions/buildah-build@v2.3
        id: docker-build
        with:
          context: ./runner
          dockerfiles: ./runner/${{ matrix.dockerfile }}
          build-args: |
            RUNNER_VERSION=${{ env.RUNNER_VERSION }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
          image: ${{ matrix.name }}
          tags: v${{ env.RUNNER_VERSION }} v${{ env.RUNNER_VERSION }}-${{ steps.vars.outputs.sha_short }} latest

      - name: Push to Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.docker-build.outputs.image }}
          tags: ${{ steps.docker-build.outputs.tags }}
          registry: ${{ env.DOCKER_QUAY_REPO }}
          username: ${{ secrets.DOCKER_QUAY_ROBOT_USERNAME }}
          password: ${{ secrets.DOCKER_QUAY_ROBOT_PASSWORD }}
