name: Test Controller

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/runners.yml'
      - '.github/workflows/on-push-lint-charts.yml'
      - '.github/workflows/on-push-master-publish-chart.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/test-entrypoint.yml'
      - '.github/workflows/wip.yml'
      - 'runner/**'
      - '**.md'
      - '.gitignore'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Controller
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set-up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18.2'
        check-latest: false
    
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install kubebuilder
      run: |
        curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.2/kubebuilder_2.3.2_linux_amd64.tar.gz
        tar zxvf kubebuilder_2.3.2_linux_amd64.tar.gz
        sudo mv kubebuilder_2.3.2_linux_amd64 /usr/local/kubebuilder

    - name: Run tests
      run: |
        make test

    - name: Verify manifests are up-to-date
      run: |
        make manifests
        git diff --exit-code
