name: CI

on:
  pull_request:
    branches:
      - master
    paths-ignore:
    - 'runner/**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install kubebuilder
      run: |
        curl -L -O https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.2.0/kubebuilder_2.2.0_linux_amd64.tar.gz
        tar zxvf kubebuilder_2.2.0_linux_amd64.tar.gz
        sudo mv kubebuilder_2.2.0_linux_amd64 /usr/local/kubebuilder
    - name: Run tests
      run: make test
    - name: Verify manifests are up-to-date
      run: |
        make manifests
        git diff --exit-code
